# API for Shodan
SHODAN_API_KEY = ''

# API for Hunter
HUNTER_API_KEY = ''

"""
API for Dehashed
DEHASHED_API_KEY -> API KEY FROM DEHASHED
DEHASHED_USER_API -> USER MAIL FROM DEHASHED
"""
DEHASHED_API_KEY = ''
DEHASHED_USER_API = ''

# API for Pipl
PIPL_API_KEY = ''

"""
API for MaxMind
MAXMIND_API_KEY -> API KEY FROM MaxMind
MAXMIND_USER_API -> USER API FROM MaxMind
"""
MAXMIND_API_KEY = ''
MAXMIND_USER_API = ''

#API for Bing 
BING_API_KEY = ''